name: Build and Deploy Web App

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build App
        run: yarn build

      - name: Save static files
        uses: actions/upload-artifact@v4
        with:
          name: static-output
          path: ./kuroshibaz.dev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download static files
        uses: actions/download-artifact@v4
        with:
          name: static-output
          path: ./kuroshibaz.dev

      - name: SSH into server and Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'kuroshibaz.dev/*'
          target: '/home/kuroshibaz/data/web/'
